services:
  api:
    container_name: api-golang
    image: api:prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      -  ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - db
    labels:
      co.elastic.logs/enabled: true
    restart: unless-stopped

  db:
    container_name: postgresdb
    image: postgres:18.1-alpine
    env_file: 
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      -  ${DB_PORT}:${DB_PORT}
    shm_size: 128mb

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.9.1
    volumes:
      - ./deploy-conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.6.1
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: unless-stopped

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.6.1
    volumes:
      - ./deploy-conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch
    restart: unless-stopped

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.6.1
    user: root
    volumes:
      - ./deploy-conf/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - logstash
    command: filebeat -e -strict.perms=false
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus

volumes:
  elasticsearch-data:
  prometheus-data:
  grafana-data: